baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Foundational Data Products Knowledge Inventory'
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "usgs"

ignoreErrors = ["error-remote-getcsv"]
